Calculate the rate law for the following reaction using the given data: 
\ce{CH3COOCH3	+ OH^- -> CH3COO^-    +  CH3OH}
\begin{center}\begin{tabular}[t]{   c  c   }
\toprule
  $t$ ( s)	&$[\ce{CH3COOCH3}]$, (M) \\
\midrule
	0	&$1.00\times10^{-2}$\\
	3	&$7.40\times10^{-3}$\\
	4	&$6.83\times10^{-3}$\\
	5	&$6.34\times10^{-3}$\\
	10	&$4.63\times10^{-3}$\\
	20	&$3.04\times10^{-3}$\\
	30&$2.24\times10^{-3}$\\
\bottomrule
\end{tabular}\end{center}
