The rate constant for the gas-phase decomposition of \ce{N2O} 
has the following temperature dependence:
\begin{center}\ce{2N2O_{(g)} ->2N2_{(g)} + O2_{(g)}}\end{center}
has the following temperature dependence:
\begin{center}\begin{tabular}[t]{   c  c   }
\toprule
  $T$ ( K)	&$k$, ($s^{-1}$) \\
\midrule
1500&	$9214$\\
1400&	$2175$\\
1300&	$411$\\
1200&   $58.9$\\
\bottomrule
\end{tabular}\end{center}
Compute the activation energy in (kJ/mol) and the frequency factor. Can you guess the reaction order?
