A is the reactant of two different reactions. Plot the data below in order to compare the rate of the two reaction.
\begin{center}\begin{tabular}[t]{  c c  c c     }
\toprule
 &Reaction I&		Reaction II	 \\
\toprule
Time, s	&	$[A]$ (M)	&		$[A]$ (M)	 \\
\midrule
0&	100	&	100	\\
1&	$7\times 10^{-1}$	&	36.78	\\
2&	$4\times 10^{-3}$	&	13.53	\\
3&	$3\times 10^{-5}$	&	4.90	\\
4&	$2\times 10^{-7}$	&	1.80	\\
\bottomrule
\end{tabular}\end{center}
