For the following elemental reaction steps indicate the molecularity and give the rate law:
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=0.5cm]	
\item \ce{N2O -> NO + O}   %molecularity=1; $r$=k[\ce{N2O}]
\item \ce{N2O + O -> N2 + O2}%molecularity=2; $r$=k[\ce{N2O}][\ce{O}]
\item \ce{2NO -> N2O2}%molecularity=2; $r$=k[\ce{NO}]
\item \ce{N2O2 + H -> N2O + HO}%molecularity=2; $r$=k[\ce{N2O2}][\ce{H}]
\end{enumerate}
