Given the following rate law
\begin{center}$r$=0.04[A]$^2$[B][C]$^3$\end{center}
indicate:
\begin{inparaenum}[(a)]
\item  the reaction order of A  % (second order)
\item  the reaction order of B  % (first order)
\item  the reaction order of C  % (third order)
\item  the overall reaction order% (sixth order)
\item  the value of the reaction constant including its units  % (0.04 s/M$^5$)
\end{inparaenum}
