Answer the following questions from the experimental data given in the table below
\begin{inparaenum}[(a)]
\item   Plot the data. Which data points are suitable for calculating initial velocities?
\item   Calculate the average initial velocity
\item   Calculate the instantaneous initial velocity
\end{inparaenum}
\begin{center}
\begin{tabular}[t]{   c  c ccccc ccc }
\toprule
\multicolumn{1}{c|}{  $t$ ( s)}	&  1	&	2	&	3	&	4	&   		6	&	7	&	9	  \\
  \midrule
  \multicolumn{1}{c|}{  $c$ (M)}&0.17 &0.24&0.31 &0.38&0.50 &0.51&0.52  \\
 
\bottomrule
\end{tabular}
\end{center}



