Classify the following chemicals in two different categories. Give a rationale for your classification. For the group with more chemicals, further classify those chemicals in two categories.
\begin{inparaenum}[(a)]
\item \ce{KCl} % (ionic, inorganic)
\item \ce{C2H2} %(covalent, organic)
\item \ce{C4H10} %(covalent, organic)
\item \ce{FeO_{(s)}} %(ionic, inorganic)
\item \ce{C6H12} %(covalent, organic)
\item \ce{PH3} %(covalent, inorganic)
\item \ce{H2O} %(covalent, inorganic)
\end{inparaenum}
