Name or formulate the following aromatic derivatives, using both the standard and the orto, meta and para nomenclature:
 \begin{center}\begin{tikzpicture}[help lines/.style={thin,draw-black!50}]
\node at (0,0) { \chemfig{**6(-(-Br)---(-Br)--)}  }; % para
\node at (0,-1.6)  {\textcolor{black}{(a)  }};
\node at (5,0) { \chemfig{**6(--(-Br)--(-NO_2)--)}  }; % meta
\node at (5,-1.6) {\textcolor{black}{(b)  }};
\end{tikzpicture}\end{center}
