Classify the following reaction as acid-base or precipitation:
\noindent
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=0.5cm]	
\item \ce{ NaCl_{(aq)} + AgNO3 _{(aq)} -> NaNO3_{(aq)} + AgCl_{(s)} v } 
\item \ce{ H2SO4_{(aq)} + 2NaOH_{(aq)} -> 2H2O_{(l)} + Na2SO4_{(aq)}     }
\item	{\raggedleft \ce{  2 Na3PO4_{(aq)} + 3 CaCl2_{(aq)} -> } }  \\ 
	\hspace*{\fill}\ce{6 NaCl_{(aq)} + Ca3(PO4)2_{(s)} v  }\\ 
\end{enumerate}
