Indicate the soluble/insoluble character of the following compounds: 
\begin{center}\begin{tabularx}{0.9\columnwidth}{>{ \arraybackslash}p{5em}>{ \arraybackslash}p{5em}>{ \arraybackslash}p{5em} }
  \toprule
\heading{Chemical} & \heading{Soluble}  &  \heading{Insoluble}      \\
    \midrule
\ce{AgNO3}	&   		&	 	       \\
 \ce{AgBr}		&  	 	& 	       \\
 \ce{CaCO3}	&  	 	&	   	       \\
\ce{Na2CO3}	&  	   	&	 	       \\
    \bottomrule
\end{tabularx}\end{center}

