The following data in cpm were taken from the background radiation measurement: 76, 127, 118, 82, 111, 155, 143, 100, 142, 112. The following results are the activity measurement for a radioactive source in cpm: 6510, 6605, 6588, 6446, 6569, 6561, 6486, 6596, 6382, 6631.
\begin{inparaenum}[(a)]
\item Compute the average activity of the background in cpm  
\item Compute the average activity of the sample, including the background in cpm  
\item Compute the average activity of the sample in cpm   
\item Compute the standard deviation of the background cpm   
\item Compute the standard deviation of the sample, including the background in cpm   
\item Compute the standard deviation of the sample in cpm   
\end{inparaenum}
