Indicate which of the following diagrams (left, center, right) represent better the following systems at equilibrium given the $K_c$ values (a, b, c). For example, you might say the "left diagram corresponds to for example (a)".
 %\begin{center}\includegraphics[width=0.4\textwidth]{../Ch-equilibrium/figure10}\end{center}
  \begin{center}
     \begin{minipage}[b]{0.9\linewidth}\resizebox{0.9\textwidth}{!}{
\begin{tikzpicture}

 \begin{scope}[rotate=00, shift={(0em,0em)}]
\draw[  black , very thick ]  (0.0,0.0) to (10.0em,0.0)    to  (10.0em,10.0em)  to  (0em,10.0em) --cycle  ;
\shade[ball color=red!10!white] (1em, 1em) circle (.2cm);\shade[ball color=red] (3em, 2.5em) circle (.2cm);\shade[ball color=red] (5em, 3.5em) circle (.2cm);\shade[ball color=red] (5em, 1.em) circle (.2cm);\shade[ball color=red] (8em, 2.em) circle (.2cm);\shade[ball color=red] (1em, 7em) circle (.2cm);\shade[ball color=red] (4em, 6em) circle (.2cm);\shade[ball color=red] (8em, 7em) circle (.2cm);
\end{scope}
 \begin{scope}[rotate=00, shift={(12em,0em)}]
\draw[  black , very thick ]  (0.0,0.0) to (10.0em,0.0)    to  (10.0em,10.0em)  to  (0em,10.0em) --cycle  ;
\shade[ball color=red!10!white] (1em, 1em) circle (.2cm);\shade[ball color=red] (3em, 2.5em) circle (.2cm);\shade[ball color=red!10!white] (5em, 3.5em) circle (.2cm);\shade[ball color=red] (5em, 1.em) circle (.2cm);\shade[ball color=red!10!white] (8em, 2.em) circle (.2cm);\shade[ball color=red] (1em, 7em) circle (.2cm);\shade[ball color=red!10!white] (4em, 6em) circle (.2cm);\shade[ball color=red] (8em, 7em) circle (.2cm); 
\end{scope}
 \begin{scope}[rotate=00, shift={(24em,0em)}]
\draw[  black , very thick ]  (0.0,0.0) to (10.0em,0.0)    to  (10.0em,10.0em)  to  (0em,10.0em) --cycle  ;
\shade[ball color=red!10!white] (1em, 1em) circle (.2cm);\shade[ball color=red!10!white] (3em, 2.5em) circle (.2cm);\shade[ball color=red!10!white] (5em, 3.5em) circle (.2cm);\shade[ball color=red] (5em, 1.em) circle (.2cm);\shade[ball color=red!10!white] (8em, 2.em) circle (.2cm);\shade[ball color=red!10!white] (1em, 7em) circle (.2cm);\shade[ball color=red!10!white] (4em, 6em) circle (.2cm);\shade[ball color=red!10!white] (8em, 7em) circle (.2cm);
\end{scope}
\end{tikzpicture}
}\end{minipage}
\end{center}
 \begin{enumerate}[(a)]	
\item	\begin{tikzpicture} \shade [ball color=red] (0:0.5) circle (0.2cm) node [shift={(2em,0)}] { \ce{<=> } } ; \shade [ball color=red!10!white] (0:2.0) circle (0.2cm);\end{tikzpicture} \hfill $K_{c}=7$  % Left
\item	\begin{tikzpicture} \shade [ball color=red] (0:0.5) circle (0.2cm) node [shift={(2em,0)}] { \ce{<=> } } ; \shade [ball color=red!10!white] (0:2.0) circle (0.2cm);\end{tikzpicture} \hfill $K_{c}=0.1$  % Right
\item	\begin{tikzpicture} \shade [ball color=red] (0:0.5) circle (0.2cm) node [shift={(2em,0)}] { \ce{<=> } } ; \shade [ball color=red!10!white] (0:2.0) circle (0.2cm);\end{tikzpicture} \hfill $K_{c}=1$  % Center
 \end{enumerate}
