The reaction of carbon monoxode with hydrogen to produce methanol has a equilibrium constant in terms of concentration that at a certain temperature is larger than one
\begin{center}\ce{CO(g) + 2H2(g) <=> CH3OH(g)} \hfill  $K_{c}=14.5$\end{center}
Calculate:
\begin{inparaenum}[(a)]
\item the equilibrium concentration of hydrogen (\ce{H2}) given that the equilibrium concentration of methanol (\ce{CH3OH}) and carbon monoxice (\ce{CO}) for the reaction is 2M, respectively. %0.034 M
\item the equilibrium concentration of hydrogen (\ce{H2}) given that the equilibrium concentration of methanol (\ce{CH3OH}) and carbon monoxide (\ce{CO}) for the reaction are 3M and 1M, respectively.  %0.46M
 \end{inparaenum}
