According to Le Ch\^{a}telier principle indicate whether the following reaction will shift in the direction of products (\ce{->}) or reactants (\ce{<-}) after the following changes: 
  \begin{center}\includegraphics[width=0.3\textwidth]{../Ch-equilibrium/figure14}\end{center}
  \begin{inparaenum}[(a)]
\item adding reactants %\ce{->}
\item increasing temperature %\ce{<-}
\item decreasing temperature% \ce{->}
 \end{inparaenum}
