Write down the expression of $K_{c}$ for the following reaction:
 \begin{enumerate}[label=(\alph*)]	
\item  \ce{2SO2_{(g)} + O2_{(g)} <=> 2SO3_{(g)}} % $K_{c}=\frac{   \big[ \ce{SO3} \big]^2    } { \big[\ce{SO2} \big]^2 \cdot \big[\ce{O2} \big]\  } $
\item  \ce{CO_{(g)} + 2H2_{(g)} <=> CH3OH_{(g)}} % $K_{c}=\frac{  \big[\ce{CH3OH} \big]  } { \big[\ce{H2} \big]^2 \cdot \big[\ce{CO} \big]\  } $
\item  \ce{C2H6_{(g)} + Cl2_{(g)} <=> C2H2Cl_{(s)} + HCl_{(g)}} %$K_{c}=\frac{   \big[ \ce{HCl} \big]    } { \big[\ce{C2H6} \big] \cdot \big[\ce{Cl2} \big]\  } $
 \end{enumerate}
