Complete the table and calculate $K_c$ and $K_p$ at 300K:
\begin{center}\begin{tabular}[t]{  cc c  c       }
\toprule
&Reaction	&	$K_c$  	&		$K_p$ \\
\midrule
(a)&\ce{2NH3_{(g)}  <=> N2_{(g)}	+ 3H2_{(g)}} &	17	&	 	\\
(b)&\ce{2SO3_{(g)}  <=> 2SO2_{(g)} + O2_{(g)}} &	0.243	&	 	\\
(c)&\ce{SO2Cl2_{(g)} <=> SO2_{(g)} + Cl2_{(g)}} &		&0.05	 	\\
(d)&\ce{Cl2_{(g)}	+ Br2_{(g)}  <=>	 2BrCl2_{(g)} } &		&0.196	 	\\
\bottomrule
\end{tabular}\end{center}
