According to Le Ch\^{a}telier principle indicate whether the following reaction will shift in the direction of products (\ce{->}) or reactants (\ce{<-}) after the following changes: 
  \begin{center}
%\includegraphics[width=0.3\textwidth]{../Ch-equilibrium/figure15}
     \begin{minipage}[b]{0.8\linewidth}\resizebox{0.9\textwidth}{!}{
\begin{tikzpicture}
 \begin{scope}[rotate=00, shift={(0em,0em)}]
\draw[  black , very thick ]  (0.0,0.0) to (10.0em,0.0)    to  (10.0em,10.0em)  to  (0em,10.0em) --cycle  ;
\shade[ball color=green!70!white] (1em, 1em) circle (.2cm);\shade[ball color=green!70!white] (3em, 2.5em) circle (.2cm);\shade[ball color=green!70!white] (5em, 3.5em) circle (.2cm);\shade[ball color=green!70!white] (5em, 1.em) circle (.2cm);\shade[ball color=green!70!white] (8em, 2.em) circle (.2cm);\shade[ball color=green!70!white] (1em, 7em) circle (.2cm);\shade[ball color=green!70!white] (4em, 6em) circle (.2cm);\shade[ball color=green!70!white] (8em, 7em) circle (.2cm);\shade[ball color=green!70!white] (5em, 9em) circle (.2cm);
\end{scope}
 \begin{scope}[rotate=00, shift={(12em,5em)}]
\draw[-Triangle, very thick](0, 0) -- (1, 0);
\end{scope}
 \begin{scope}[rotate=00, shift={(17em,0em)}]
\draw[  black , very thick ]  (0.0,0.0) to (10.0em,0.0)    to  (10.0em,10.0em)  to  (0em,10.0em) --cycle  ;
\shade[ball color=red!10!white] (1em, 1em) circle (.2cm);\shade[ball color=red!10!white] (3em, 2.5em) circle (.2cm);\shade[ball color=red!10!white] (5em, 3.5em) circle (.2cm);\shade[ball color=red!10!white] (5em, 1.em) circle (.2cm);\shade[ball color=red!10!white] (9em, 2.em) circle (.2cm);\shade[ball color=red!10!white] (1em, 7em) circle (.2cm);\shade[ball color=red!10!white] (4em, 6em) circle (.2cm);\shade[ball color=red!10!white] (8em, 7em) circle (.2cm);\shade[ball color=red!10!white] (5em, 9em) circle (.2cm);
\end{scope}
 \begin{scope}[rotate=00, shift={(12em,-1em)}]
\newcommand\allumette[2]{
}
\allumette{0.1}{0.2}
\filldraw[orange,scale=0.5,shift={(8.2,1.2)}]  (0,0) .. controls (-1.5,1.25) and (.5,2) .. (-.2,4) .. controls (1,2.5) and (1,.5) .. (0,0);
\end{scope}
\end{tikzpicture}
}\end{minipage}
\end{center}
  \begin{inparaenum}[(a)]
\item adding reactants %\ce{->}
\item increasing temperature %\ce{<-}
\item decreasing temperature% \ce{->}
 \end{inparaenum}
