For the reactions below indicate whether they will evolve towards the right or towards the left in order to reach equilibrium.
\begin{center}\begin{tabular}[t]{  ll c  c        }
\toprule
&Reaction	&	$K_c$  	&		$Q$  \\
\midrule
(a)&\ce{2NH3_{(g)}  <=> N2  + 3H2 } &	17	&	20  	\\
(b)&\ce{2SO3_{(g)}  <=> 2SO2_{(g)} + O2_{(g)} } &	0.243	&10	  	\\
(c)&\ce{H2_{(g)}  + I2  <=>2HI_{(g)}   } &	50	&0.1	 	 \\
(d)&\ce{H2O_{(l)} <=>H2O_{(g)}      } &	0.196	&0.196 	 	\\
\bottomrule
\end{tabular}\end{center}
