True or false:\begin{inparaenum}[(a)]
\item  At equilibrium, the rate of the reverser reaction is twice the rate of the forward reaction %(False)
\item  At equilibrium, the concentration of products do not change	%(False)
\item  At equilibrium, the concentration of reactants do not change	%(False)
\item  At equilibrium, the concentration of reactants and products do not change %(True)
 \end{inparaenum}
