Combine the following ions:
\begin{multicols}{2}
  \noindent
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=.5cm]
 \item \ce{Na^{+}} + \ce{PO4^{3-}}   %(\ce{Na3PO4})
\item \ce{Li^{+}} + \ce{MnO4^{-}}   %(\ce{LiMnO4})
\item \ce{Mg^{2+}} + \ce{NO3^{-}}   %(\ce{Mg(NO3)2})
\item \ce{Ca^{2+}} + \ce{CO3^{2-}}   %(\ce{CaCO3})
\item \ce{Cs^{+}} + \ce{Cr2O7^{2-}}   %(\ce{Cs2Cr2O7})
\item \ce{K^{+}} + \ce{BO3^{3-}}   %(\ce{K3BO3})
\end{enumerate}
\end{multicols}    
