Classify the following chemicals in two groups. Justify your classification.
\begin{multicols}{3}
  \noindent
  \begin{enumerate} [topsep=0pt, partopsep=0pt, label=(\alph*), leftmargin=.5cm]
\item \ce{NaCl}  %(group ionic type I)
\item \ce{MnO2} %(group ionic type II)
\item \ce{FeCl3} %(group ionic type II)
\item \ce{SrO} %(group ionic type I)
\item \ce{Li3N} %(group ionic type I)
\item \ce{NiO} %(group ionic type II)
\end{enumerate}
\end{multicols}    
