For the galvanic cell below, indicate:  \begin{inparaenum}[(a)]
\item label the sign ($-$ or $+$) of each electrode
\item identify the flow of electrons
 \end{inparaenum}
 \begin{center}
 \begin{tikzpicture}
\colorlet{batteryLeftElectrode}{green!75}
\colorlet{batteryLeftSolution}{green!15}
\colorlet{batteryRightElectrode}{yellow!75}
\colorlet{batteryRightSolution}{yellow!15}
 \batterya{ }{ }	{  }	{ }{2}{\Large Cathode}{\Large Anode}{V}{1}    % 1 to the right
 \end{tikzpicture}
\end{center}
