Compare the acidity of the following pairs and justify the mechanism responsible for your choice:
\begin{enumerate}[label=(\alph*)]
\item \ce{H2O} and \ce{H2S}% (\ce{H2S} due to MW of central atom)
\item \ce{SiH4} and \ce{PH3}% (\ce{PH3} due to electronegativity of central atom)
\item \ce{CH3COOH} and \ce{CH2FCOOH}% (\ce{CH2FCOOH} due indirect electronegative atom)
\item \ce{CH2ClCOOH} and \ce{CH2FCOOH}% (\ce{CH2FCOOH} due indirect electronegative atom)
 \end{enumerate}
