We 10mL of titrate a 0.1M-HCl solution with 0.05M-NaOH using an indicator with $K_{In}=1\times 10^{-7}$ that is blue on its acid form and red on its basic form. Answer the following questions:
\begin{inparaenum}[(a)]
\item  What is the initial color of the solution  	%blue
\item  After adding 20mL of NaOH, indicate the color of the solution  	%green
\item  After adding 30mL of NaOH, indicate the color of the solution  	%red
\item  What is the PH of the equivalency point  	%PH=7
\item  At what PH will the color transition occur  	%PH=6 using the 10\% rule.
 \end{inparaenum}
