Calculate the PH for the following scenarios:
\begin{inparaenum}[(a)]
\item A 0.8 M-\ce{HF}/0.1M-\ce{NaF}, $K_a=6.30 \times 10^{-4}$ buffer  %(PH=2.30 )
\item A 0.8 M-\ce{HF}/0.1M-\ce{NaF}, $K_a=6.30 \times 10^{-4}$ buffer after adding 1mL of 0.1HCl into 2mL of the buffer %(PH=1.97)
\item A 0.8 M-\ce{HF}/0.1M-\ce{NaF}, $K_a=6.30 \times 10^{-4}$ buffer after adding 1mL of 0.1NaOH into 2mL of the buffer %(PH=2.50)
\item Is the buffer more resistant to acids or bases, and why?
 \end{inparaenum}
