Complete the following unit conversion:
  \noindent
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=1cm]
  \item $0.5\cancel{ \mu \text{g}} \times \dfrac{  \hlmath{\hspace{35pt}}  \text{g}}{\hlmath{\hspace{35pt}} \cancel{ \mu \text{g}}}= \hlmath{\hspace{35pt}}   \text{g}$
\item $125\cancel{ \text{L}} \times \dfrac{  \hlmath{\hspace{35pt}}  \text{mL}}{\hlmath{\hspace{35pt}} \cancel{ \text{L}}}= \hlmath{\hspace{35pt}}   \text{mL}$
  \end{enumerate}
