Fill the gap in the following unit conversion:
\begin{center}$70\cancel{cm} \times \dfrac{ \hlmath{\hspace{35pt}}m }{1\cancel{cm}}=0.7m$\end{center}
%\begin{multicols}{2}
%  \noindent
%  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=1cm]
%\item $1\times 10^{-2}$
%\item $1\times 10^{-3}$
%\item $1\times 10^{2}$
%\item $1\times 10^{3}$
%\item $1\times 10^{-6}$
%\end{enumerate}
%\end{multicols}    
