Classify the following objects as an element, compound, and homogeneous mixture, a heterogeneous mixture or none of the others:
\begin{inparaenum}[(a)]
  \item an energy drink %(Homogeneous mixture)
  \item helium (a gas) %(element)
    \item sulfur (a solid) %(element)
  \item milk %(homogeneous mixture)
  \item milkshake %(Homogeneous mixture)
    \item gelato %(Homogeneous mixture)
    \item  air %(Homogeneous mixture)
 \item  granite %(Heterogeneous mixture)
  \item uranium (a solid) %(element)
\end{inparaenum}
