Carry the following calculations with the correct number of digits or significant figures:
  \begin{multicols}{2} \noindent
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=1cm]
  \item $0.2301+0.123$	 \iffalse $0.353$ \fi
  \item $0.2301-1.12$	\iffalse $-0.89$ \fi
    \item $ 88.1-87.57$	\iffalse $=0.5$ \fi
  \item $24.56+2.4$	\iffalse $=27.0$ \fi
  \end{enumerate}\end{multicols}
