Fill the gap in the following unit equalities or conversion factors:
\begin{inparaenum}[(a)]
\item $1Tm=\hlmath{\hspace{35pt }}$m
\item  $1dm=\hlmath{\hspace{35pt }}$m
\item   $1cg=\hlmath{\hspace{35pt }}$g
\item   $1ms=\hlmath{\hspace{35pt }}$s
%\item  $1kcal=\hlmath{\hspace{35pt }}$cal
\item  $1qt=\hlmath{\hspace{35pt }}$mL
\item  $1L=\hlmath{\hspace{35pt }}dm^3$
\item  $1lb=\hlmath{\hspace{35pt }}$g
\item  $1in=\hlmath{\hspace{35pt }}$cm
\end{inparaenum}
