The lattice energy of NaF, the solute, is -910 KJ/mol, whereas the enthalpy of hydration of \ce{Na^+} and \ce{F^-} are -406 and -524 KJ/mol, respectively.
\begin{inparaenum}[(a)]
\item   Calculate the hydration energy of \ce{NaF}  % -930 KJ/mol
\item   Calculate the energy needed to expand the solute  % 910 KJ/mol
\item   Calculate the enthalpy of solution. Is the dissolution endothermic or exothermic?  % -20 KJ/mol ; exothermic
 \end{inparaenum}
