We measured the change of the boiling point of a solution with concentration at a fixed temperature. Use the data below to experimentally compute $i\cdot k_b$ for the solution and the boiling point of the pure solvent. Assume $i\cdot k_b$ does not change for the molarity range given.
\begin{center}\begin{tabular}[t]{  c c    }
\toprule
  m	&$T_b$ ($^{\circ}$C) \\
\midrule
 0.010	&208.059 	 \\
 0.011	& 208.065 	 \\
 0.012	&208.071 	 \\
 0.013	&208.076   \\
  0.014	&208.083  	 \\
\bottomrule
\end{tabular}\end{center}
