Use the List feature of your graphing calculator to fill the table below carrying calculations in bulk: 
\begin{center}\resizebox{\columnwidth}{!}{\begin{tabular}[t]{  c c c c c   }
\toprule
 Solution &g  &   g &  \%$_{solute}$	& \%$_{solvent}$\\
  &solute  &   solvent &   	&  \\
 \midrule
 a	&10    &10    &    	&   \\
 b	&20    &9    &    	&   \\
 c	&30    &8    &    	&   \\
 d	&40    &7    &    	&   \\
 e	&50    &6    &    	&   \\
 f	&60    &5    &    	&   \\
\bottomrule
\end{tabular}}\end{center}
