From the following solutions:
\begin{inparaenum}[(i)]
\item     0.2m \ce{LiF}  in water  %0.4
\item     0.1m \ce{HF}  in water %0.1
\item     0.3m \ce{Na_2SO_4}  in water %1
\end{inparaenum}
select the one with:
\begin{inparaenum}[(a)]
\item     lowest freezing point   %0.3m \ce{Na_2SO_4}  in water  
\item     highest freezing point  % 0.1m \ce{HF}  in water 
\item     highest boiling point     %0.3m \ce{Na_2SO_4}  in water  
\item     lowest boiling point      % 0.1m \ce{HF}  in water    
\item     lowest vapor pressure  %0.3m \ce{Na_2SO_4}  in water 
 \item    highest vapor pressure  % 0.1m \ce{HF}  in water   
 \item    highest osmotic pressure %0.3m \ce{Na_2SO_4}  in water   
 \item    lowest osmotic pressure %  0.1m \ce{HF}  in water 
\end{inparaenum}
