Which of the species of the following pairs would you expect to have a larger, more positive, enthalpy of expansion-- defined in the context of hydration enthalpy, as the energy needed to separate the molecules of a compound into its gas state?
\begin{inparaenum}[(a)]
\item   \ce{H2O_{(l)}} or \ce{CaCl2_{(s)}}  %		\ce{CaCl2_{(s)}}  
\item   \ce{CH3(CH2)2CH3_{(g)}} or \ce{CH3(CH2)9CH3_{(g)}}  %		\ce{CH3(CH2)9CH3_{(g)}} 
\item   \ce{H2O_{(l)}} or \ce{SO2_{(g)}}  %				\ce{H2O_{(l)}}
 \end{inparaenum}
