The vapor pressure of acetone and chloroform at 35$^{\circ}$C are 345 and 293 torr, respectively. Calculate the corresponding vapor pressure of the following mixtures of both at 35$^{\circ}$C, assuming the mixture is ideal:
\begin{inparaenum}[(a)]
\item     1 mol of acetone with 1 mole of chloroform %319.0 torr
\item     2 mol of acetone with 1 mole of chloroform %327.6 torr
\item     1 mol of acetone with 2 mole of chloroform %425.3 torr
\end{inparaenum}
