We measured the change of osmotic pressure with concentration for a given solute at a fixed temperature. Use the data below to experimentally compute van't Hoff's factor $i$ for an unknown solute at 25$^{\circ}$C given that R is 62.32 torr/(mol$\cdot$ K). Assume $i$ does not change for the molarity range given.
\begin{center}\begin{tabular}[t]{  c c    }
\toprule
  M	&$\Pi$ (torr) \\
\midrule
 0.010	&464 	 \\
 0.011	& 511	 \\
 0.012	&557 	 \\
 0.013	&603  \\
  0.014	&650 	 \\
\bottomrule
\end{tabular}\end{center}
