Which of the following mixtures would you expect to give the most ideal solution:
\begin{inparaenum}[(a)]
 \item    \ce{CH_3OH}   and \ce{H_2O} or   \ce{CH_3COCH_3}   and \ce{H_2O} % \ce{CH_3OH}   and \ce{H_2O}
 \item  0.001M \ce{KOH} solution     or  0.001M \ce{Ca(OH)2} solution  in water   %0.001M \ce{KOH} solution
 \item    \ce{CH_3F}   and \ce{HF} or   \ce{CH_4}   and \ce{CH_3CH_3} %\ce{CH_4}   and \ce{CH_3CH_3} 
\end{inparaenum}
