Data below lists the vapor pressure of mixtures of benzene and ethylene chloride at fixed temperature. 
\begin{center}
%\resizebox{\columnwidth}{!}{
\begin{tabular}[t]{  c c c    }
\toprule
 Mixture &$\chi_{\ce{C2H5Cl}}$  &   P (torr)  \\
 \midrule
 a	&0.0    &268        \\
 b	&0.25    &260         \\
 c	&0.50    & 252        \\
 d	&0.75    &244         \\
 e	&1.00    &236         \\
 \bottomrule
\end{tabular}
%}
\end{center}
Answer the following questions:
\begin{inparaenum}[(a)]
\item  Which solution will have the lowest normal boiling point % a
\item  Which solution will have the hightest normal boiling point % e
\item  Estimate the sign of $\Delta H_{sol}$ % $\sim 0$
\item Are the intermolecular forces weaker,  stronger or similar than those of the pure substances  % similar
\end{inparaenum}
