You have a solution (0.01M) in contact with the pure solvent separated by a semipermeable membrane. We apply a series of external pressure to the solution at 25$^{\circ}$C. Indicate for each pressure, if this will stop the osmotic flow of water, assuming the van't Hoff factor to be one:
\begin{inparaenum}[(a)]
\item   0.24 atm	% yes, it will stop the flow
\item   0.02 atm	% no 
\item   0.22 atm % no
\item   0.29 atm %  it will produce reverse osmosis
 \end{inparaenum}
