Data below lists the vapor pressure of mixtures of acetone (\ce{(CH3)2CO}) and chloroform (\ce{CHCl3}) at 308.32 K temperature. 
\begin{center}
%\resizebox{\columnwidth}{!}{
\begin{tabular}[t]{  c c c    }
\toprule
 Mixture &$\chi_{\ce{CHCl3}}$  &   P (torr)  \\
 \midrule
 a	&0.0    &350        \\
 b	&0.25    &  300       \\
 c	&0.50    &  260        \\
 d	&0.75    &  250        \\
 e	&1.00    &285         \\
 \bottomrule
\end{tabular}
%}
\end{center}
Answer the following questions:
\begin{inparaenum}[(a)]
\item  Which solution will have the lowest normal boiling point % a
\item  Which solution will have the hightest normal boiling point % e
\item  Estimate the sign of $\Delta H_{sol}$ % <0
\item Are the intermolecular forces weaker,  stronger or similar than those of the pure substances  %stronger
\end{inparaenum}
