From the following solutions:
\begin{inparaenum}[(i)]
\item     0.1m \ce{C_6H_{12}O_6}  in water
\item     0.1m \ce{KCl}  in water
\item     0.1m \ce{K_2SO_4}  in water
\end{inparaenum}
select the one with:
\begin{inparaenum}[(a)]
\item     lowest freezing point   % \ce{K_2SO_4}  in water  
\item     highest freezing point  % 0.1m \ce{C_6H_{12}O_6}  in water 
\item     highest boiling point     % \ce{K_2SO_4}  in water 
\item     lowest boiling point      %  0.1m \ce{C_6H_{12}O_6}  in water
\item     lowest vapor pressure  % \ce{K_2SO_4}  in water 
 \item    highest vapor pressure  %  0.1m \ce{C_6H_{12}O_6}  in water
 \item    highest osmotic pressure % \ce{K_2SO_4}  in water 
 \item    lowest osmotic pressure % 0.1m \ce{C_6H_{12}O_6}  in water 
\end{inparaenum}
