Which of the species of the following pairs would you expect to have a larger, more positive, enthalpy of hydration, corresponding to a less favored hydration?
\begin{inparaenum}[(a)]
\item   \ce{Na^{+}} or \ce{Mg^{2+}}   %  \ce{Mg^{2+}} 
\item   \ce{H^{+}} or \ce{NH4^{+}}   %   \ce{NH4^{+}}
\item   \ce{Mg^{2+}} or \ce{Ca^{2+}}   %  \ce{Ca^{2+}} 
\item   \ce{Cl^{-}} or \ce{ClO4^{-}}   %  \ce{ClO4^{-}}
 \end{inparaenum}
