Which of the following solutions will have a lower vapor pressure:
\begin{inparaenum}[(a)]
\item   Pure water at 25$^{\circ}$C
\item   Pure water at 98$^{\circ}$C
\item   A solution of \ce{C_6H_{12}O_6} in water with $\chi_{\ce{C_6H_{12}O_6}}$=0.1 at 25$^{\circ}$C
\item   A solution of \ce{C_6H_{12}O_6} in water with $\chi_{\ce{C_6H_{12}O_6}}$=0.01 at 25$^{\circ}$C
\item   A solution of \ce{KCl} in water with $\chi_{\ce{KCl}}$=0.01 at 25$^{\circ}$C
\item   A solution of \ce{KCl} in water with $\chi_{\ce{KCl}}$=0.1 at 15$^{\circ}$C
 \end{inparaenum}
