Use the List feature of your graphing calculator to fill the table below carrying calculations in bulk (these are water-based solutions): 
\begin{center}\resizebox{\columnwidth}{!}{\begin{tabular}[t]{  c c c c c   }
\toprule
 Solute&Xylene  &   toluene &  benzene	& styrene\\
 \midrule
 MW (g/mol)	&106   &92    &78   	&104	  \\
 d (g/mL)	&1.1   &1.3    &1.5   	&  1.7 \\
 m		&1.1   &0.9    &0.8   	& 0.7 \\
 M		&   &    &   	&  \\
 \%$_m$		&   &    &   	&  \\
 $\chi$		&   &    &   	&  \\
\bottomrule
\end{tabular}}\end{center}
