For the following colloids, indicate the nature of the dispersed and dispersing medium (liquid, solid or gas) : 
\begin{inparaenum}[(a)]	
\item  soda water % (dispersed: gas ; dispersing: liquid)
\item  cake % (dispersed: gas ; dispersing: solid)
\item  midst % (dispersed: liquid ; dispersing: gas)
\item  smoke % (dispersed: solid ; dispersing: gas)
\item  froth % (dispersed: gas ; dispersing: liquid)
 \end{inparaenum}
