We measured the change of the freezing point of a solution with concentration at a fixed temperature. Use the data below to experimentally compute $i\cdot k_f$ for the solution and the freezing point of the pure solvent. Assume $i\cdot k_b$ does not change for the molarity range given.
\begin{center}\begin{tabular}[t]{  c c    }
\toprule
  m	&$T_f$ ($^{\circ}$C) \\
\midrule
 0.010	&-23.30 	 \\
 0.011	& -23.33	 \\
 0.012	&-23.36 	 \\
 0.013	&-23.39   \\
  0.014	&-23.41 	 \\
\bottomrule
\end{tabular}\end{center}
