Classify as: \\
\begin{inparaenum}[(i)]
\item Foam colloid
\item Solid foam colloid
\item Aerosol colloid
\item Emulsion colloid
\item Gel colloid
\item Sol colloid
\item Solid-sol colloid
\item A solution
 \end{inparaenum}
\\ the following series of mixtures:\\
\begin{inparaenum}[(a)]	
\item  	Soda %solution
\item  	Soap Lather %Foam
\item  	Whipped cream  %Foam
\item  	Pumice stone 	%Solid foam
\item  	Rubber	%Solid foam
\item  	Cloud 		%Aerosol
\item  	 Mist 		%Aerosol
\item  	  Fog		%Aerosol
\item  Milk 	%Emulsion	
\item   Cream 	%Emulsion	
 \end{inparaenum}
