Draw  electron-dot structures for the following molecules given that the first atom listed is the central atom. Some of the atoms might not obey the octet rule. If the species has a charge indicate the location of the charge:
\begin{inparaenum}[(a)]
 \item  \ce{I3^-}	  	%\hspace{.05in} \schemestart \chemleft[\hspace{.4cm}\chemfig{\chemabove{\lewis{136,I}}{\hspace{.1cm} \ominus }	( (-[:0]\lewis{206,I})(-[:180]\lewis{246,I}) )}\hspace{.4cm}\chemright] \chemmove{\node[] at (0pt,5pt) {\footnotesize $-$};}\schemestop  \hspace{.05in}
 \item  \ce{Br3^-}	  %\hspace{.05in} \schemestart \chemleft[\hspace{.4cm}\chemfig{\chemabove{\lewis{136,Br}}{\hspace{.1cm} \ominus }	( (-[:0]\lewis{206,Br})(-[:180]\lewis{246,Br}) )}\hspace{.4cm}\chemright] \chemmove{\node[] at (0pt,5pt) {\footnotesize $-$};}\schemestop  \hspace{.05in}
  \item  \ce{SF6} 	  %\hspace{.05in}\chemfig{S( (-[:340]\lewis{026,F}) (-[:60]\lewis{024,F})  (-[:120]\lewis{240,F})(-[:190]\lewis{462,F})(-[:250]\lewis{064,F})(-[:300]\lewis{064,F})	)}\hspace{.05in} 
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
