Given the following Lewis structures, predict the molecular geometry and angles:
\vspace{0.5cm}\begin{multicols*}{2}
\begin{enumerate}[label=(\alph*)]
   \item   \hspace{.05in}\chemfig{Cl( (=[:0]\lewis{17,O})  (=[:90]\lewis{13,O})(-[:180]\lewis{246,O})(=[:270]\lewis{57,O})	)}\hspace{.05in}	%\ce{AB4}; tetrahedral; 109.5$^{\circ}$
  \item   \hspace{.05in}\chemfig{Be( (-[:45]H)(-[:135]H) )}\hspace{.05in} %\ce{AB2}; linear; 180$^{\circ}$
   \end{enumerate}
\end{multicols*}
