Given the following Lewis structures, predict the molecular geometry and angles:
\vspace{0.5cm}\begin{multicols*}{2}
\begin{enumerate}[label=(\alph*)]
  \item  \hspace{.05in}\chemfig{\lewis{26,Se}( (-[:45]\lewis{713,Cl})(-[:135]\lewis{513,Cl}) )}\hspace{.05in}	% \ce{AB2E2}; bent; 109$^{\circ}$
 \item   \hspace{.05in}\chemfig{C( (=[:90]\lewis{13,O})(-[:210]H)(-[:330]H))}\hspace{.05in}   % \ce{ABE3}; planar trigonal; 120$^{\circ}$
 \end{enumerate}
\end{multicols*}
