Draw  electron-dot structures for the following molecules that obey the octet rule, given that the first atom listed is the central atom:
\begin{inparaenum}[(a)]
   \item  \ce{HCN}	  %\hspace{.05in}\chemfig{H-[:0]C~[:0]\lewis{0,N} }\hspace{.05in}
  \item  \ce{CO2}	  %\hspace{.05in}\chemfig{C( (=[:0]\lewis{17,O})(=[:180]\lewis{35,O}) )}\hspace{.05in}
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
