Indicate the charge of the atom marked blue in the following electron-dot structure that follow the octet rule:
\vspace{0.3cm}\begin{multicols*}{2}
\begin{enumerate}[label=(\alph*)]
\item   	   \hspace{.05in}\chemfig{{\color{blue}P}( (-[:90]\lewis{024,O})  (-[:210]\lewis{460,Cl})(-[:270]\lewis{460,Cl})(-[:320]\lewis{062,Cl})	)}\hspace{.05in}   % $+1$
\item       \hspace{.05in}\chemfig{{\color{blue}Cl}( (-[:0]\lewis{620,O})  (-[:90]\lewis{024,O})(-[:180]\lewis{246,O})(-[:270]\lewis{064,O})	)}\hspace{.05in} % $+3$
  \end{enumerate}
\end{multicols*}
