Draw  electron-dot structures for the following molecules that obey the octet rule, given that the first atom listed is the central atom:
\begin{inparaenum}[(a)]
   \item  \ce{NH3}	  %\hspace{.05in}\chemfig{\lewis{2,N}( (-[:185]H)(-[:270]H)(-[:355]H) )}\hspace{.05in}
 \item  \ce{NCl3}	  %\hspace{.05in}\chemfig{\lewis{2,N}( (-[:185]\lewis{246,Cl})(-[:270]\lewis{460,Cl})(-[:355]\lewis{602,Cl}) )}\hspace{.05in}
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
