Draw  electron-dot structures for the following molecules that obey the octet rule, given that the first atom listed is the central atom:
\begin{inparaenum}[(a)]
  \item  \ce{ICl}	  %\hspace{.05in}\chemfig{\lewis{246,I}( (-[:0]\lewis{026,Cl}) )}\hspace{.05in}
 \item  \ce{HI}	  %\hspace{.05in}\chemfig{H( (-[:0]\lewis{026,I}) )}\hspace{.05in}
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
