Draw  electron-dot structures for the following molecules given that the first atom listed is the central atom. Some of the atoms might not obey the octet rule. If the species has a charge indicate the location of the charge:
\begin{inparaenum}[(a)]
\item  \ce{BH3} 	   	%\hspace{.05in}\chemfig{B( (-[:0]H)(-[:180]H)(-[:270]H))}\hspace{.05in} 
 \item  \ce{BH2F} 	  %\hspace{.05in}\chemfig{B( (-[:0]H)(-[:180]H)(-[:270]\lewis{460,F}))}\hspace{.05in} 
 \item  \ce{POCl3} 	  %\hspace{.05in}\chemfig{P( (=[:90]\lewis{13,O})  (-[:210]\lewis{460,Cl})(-[:270]\lewis{460,Cl})(-[:320]\lewis{062,Cl})	)}\hspace{.05in} 
 \item  \ce{ClO4^-} 	  %\hspace{.05in}\chemfig{Cl( (=[:0]\lewis{17,O})  (=[:90]\lewis{13,O})(-[:180]\lewis{246,O})(=[:270]\lewis{57,O})	)}\hspace{.05in} 
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
