Indicate the charge of the atom marked blue in the following electron-dot structure:
\vspace{0.3cm}\begin{multicols*}{2}
\begin{enumerate}[label=(\alph*)]
\item \chemleft[\chemfig{\lewis{2,{\color{blue}C}}( (-[:0]H)(-[:180]H)(-[:270]H))}\chemright] \chemmove{\node[] at (0pt,15pt) {\footnotesize $ $};}
\item \chemleft[\chemfig{\lewis{2,{\color{blue}O}}( (-[:0]H)(-[:180]H)(-[:270]H))}\chemright]
\chemmove{\node[] at (0pt,15pt) {\footnotesize $ $};}
\end{enumerate}\end{multicols*}
