Draw  electron-dot structures for the following molecules that obey the octet rule, given that the first atom listed is the central atom:
\begin{inparaenum}[(a)]
\item  \ce{F2}	  %\hspace{.05in}\chemfig{\lewis{246,F}( (-[:0]\lewis{026,F}) )}\hspace{.05in}
 \item  \ce{O2}	  %\hspace{.05in}\chemfig{\lewis{35,O}( (=[:0]\lewis{17,O}) )}\hspace{.05in}
\end{inparaenum}
\begin{center}\begin{tikzpicture}
\draw[step=.25cm,gray,very thin] (-4,-3) grid (4,3);
\end{tikzpicture}\end{center}
