Given the following Lewis structures, predict the molecular geometry and angles:
\vspace{0.5cm}\begin{multicols*}{2}
\begin{enumerate}[label=(\alph*)]
  \item   \hspace{.05in}\chemfig{\lewis{13,Cl}( (-[:185]\lewis{046,F})(-[:270]\lewis{046,F})(-[:355]\lewis{046,F}) )}\hspace{.05in}	%\ce{AB3E2}; T-shaped; 180$^{\circ}$ and 90$^{\circ}$
  \item   \hspace{.05in} \schemestart \chemleft[\hspace{.4cm}\chemfig{\chemabove{\lewis{136,Br}}{\hspace{.1cm} \ominus }	( (-[:0]\lewis{206,Br})(-[:180]\lewis{246,Br}) )}\hspace{.4cm}\chemright] \chemmove{\node[] at (0pt,5pt) {\footnotesize $-$};}\schemestop  \hspace{.05in} %\ce{AB2E3}; linear; 180$^{\circ}$  
  
 \end{enumerate}
\end{multicols*}
