Fill the conversion factor that calculates the final property, given that the molar mass of \ce{C2H6} is 30g/mol:
 \begin{equation*}\begin{split}
7\times 10^{21} \text{ atoms of }\ce{C}
\times 
\dfrac{\hlmath   {\hspace{35pt}}  }
{\hlmath{\hspace{35pt}}     }
\times
\dfrac{\hlmath{\hspace{35pt}}}
{\hlmath{\hspace{35pt}}} \\
=\hlmath{\hspace{35pt}}   \text{ moles of }\ce{C2H6}
\end{split}\end{equation*}
