Fill the conversion factor that calculates the moles of \ce{AgO} produced from 10 moles of oxygen:
\begin{center}\ce{ 2Ag(s) + O2(g) -> 2AgO(s)  }\end{center}
 \begin{equation*}\begin{split}
10\cancel{\text{ moles of }\ce{O2}} \times \dfrac{\hlmath{\hspace{35pt}}\text{ moles of }\ce{AgO}}{\hlmath{\hspace{35pt}}\cancel{\text{ moles of }\ce{O2}}}\\
=20\text{ moles of }\ce{AgO}.
\end{split}\end{equation*}
