Fill the conversion factor that calculates the moles of oxygen needed to react with 2 moles of Silver producing \ce{AgO}:
\begin{center}\ce{ 2Ag(s) + O2(g) -> 2AgO(s)  }\end{center}
 \begin{equation*}\begin{split}
2\cancel{\text{ moles of }\ce{Ag}} \times \dfrac{\hlmath{\hspace{35pt}}\text{ moles of }\ce{O2}}{\hlmath{\hspace{35pt}}\cancel{\text{ moles of }\ce{Ag}}}\\
=1\text{ moles of }\ce{O2}.
\end{split}\end{equation*}
