Classify next reaction as combination, decomposition, single replacement, double replacement, or combustion:
\noindent
  \begin{enumerate} [topsep=0pt, partopsep=1pt, label=(\alph*), leftmargin=0.5cm]	
\item  \ce{Pb_{(s)} + FeSO4_{(s)} -> PbSO4_{(s)} + Fe_{(s)}}
\item	\ce{C6H12_{(g)} + 9O2_{(g)} -> 6CO2_{(g)} + 6H2O_{(g)}}
\item	{\raggedleft \ce{2RbNO3_{(aq)} + BeF2_{(aq)}}}  \\ 
	\hspace*{\fill}\ce{-> Be(NO3)2_{(aq)} + 2RbF_{(aq)}} 
\end{enumerate}
