Which of these electron transitions correspond to absorption of energy and which to emission?
\begin{enumerate}[label=(\alph*)]\begin{multicols*}{2}
\item $\Delta E_{1\rightarrow 2}$  %absorption 
\item $\Delta E_{2\rightarrow 1}$	%Emission
\item $\Delta E_{3\rightarrow 1}$	%Emission
\item  $\Delta E_{3\rightarrow 5}$	%absorption
\item $\Delta E_{5\rightarrow 3}$	%Emission
\item $\Delta E_{1\rightarrow 3}$	%absorption
\end{multicols*}\end{enumerate}
