Answer the following questions:\begin{inparaenum}[(a)]
\item Calculate the standard reduction potential for the \ce{Li}/\ce{Li^{+}} pair given that the standard formation Gibbs free energy of formation \ce{Li^{+}} is 193KJ/mol. %-3.04V 
\item Calculate the standard reduction potential for the \ce{Na}/\ce{Na^{+}} pair given that the standard formation Gibbs free energy of formation \ce{Na^{+}} is 261KJ/mol. %-2.71V 
 \end{inparaenum}
