For the galvanic cell below, compute: 
\begin{inparaenum}[(a)]
 \item the standard potential, given $\mathcal{E}^{\circ}$(\ce{	Sn^{2+}	}/\ce{Sn}) =$-$0.14V and $\mathcal{E}^{\circ}$(	\ce{	Br2} 	/\ce{Br^-})=$+$1.09V
\item the potential at the given concentrations and 298.15K
\end{inparaenum} 

  \begin{center} \ce{Sn_{(s)} }\hspace{.02 in}|\hspace{.02 in} \ce{Sn^{2+}}\text{($10^{-6}$ M)}\hspace{.02 in}||\hspace{.02 in}\ce{Br^{-}    }\text{($10^{-2}$ M)}\hspace{.02 in}|\hspace{.02 in}\ce{Br_{(l)}}\end{center}	 

