Give the line notation for the galvanic cell below:
 \colorlet{batteryLeftElectrode}{red!75}
 \colorlet{batteryRightElectrode}{green!75}
 \colorlet{batteryLeftSolution}{blue!15}
 \colorlet{batteryRightSolution}{green!15}
 \renewcommand{\Helectrodelabel}{\small \ce{ }}
 \begin{center}\begin{tikzpicture}
 \batterya{\small \ce{OH^-(1M)}}{\small \ce{Ba(OH)2} \\ \ce{+ Ba}}	{Pt }	{	 \small \ce{Ag^{2+}(1M)} + \ce{Ag^+(1M)} 	 }{0}{ }{ }{V}{1}    % 1 to the right
  \end{tikzpicture}\end{center}
