For the galvanic cell below, indicate:  \begin{inparaenum}[(a)]
\item label the anode
\item label the cathode
 \end{inparaenum}
 \begin{center}
 \begin{tikzpicture}
\colorlet{batteryLeftElectrode}{brown!75}
\colorlet{batteryLeftSolution}{brown!15}
\colorlet{batteryRightElectrode}{pink!75}
\colorlet{batteryRightSolution}{pink!15}
 \batterya{ }{ }	{  }	{ }{2}{\Large $-$}{\Large $+$}{V}{1}    % 1 to the right
 \end{tikzpicture}
\end{center}
