We want to build up a galvanic cell based on the reactions below.  
\begin{center}\ce{	Li^+ + C6_{(s)} +e^-	 <=>	LiC6_{(s)} 	}\hfill $\mathcal{E}^{\circ} =-$2.84V\\
\ce{	N2_{(g)} + 2H2O + 6H+ + 6e^-	 <=>	2NH4OH_{(aq)}	 }\hfill $\mathcal{E}^{\circ} =+$0.09V\end{center} 
Indicate:
\begin{inparaenum}[(a)]
\item the anodic and cathodic reactions
\item the balanced overall redox
\item the number of electrons flowing 
\item the overall voltage of the cell
 \end{inparaenum}
